# -*- coding: utf-8 -*-
"""Loan_Model_NN_RF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieqpNpmtm30Do4-RsBPBRdrvGRejV-Ju

# Instructions

1. Make sure to save your desired NN architecture using the "SAVE" button. Follow the cell order in the notebook.

![Grafico de Red](https://imgur.com/6im6PUB.png)

2. When configuring the network architecture, do not forget to press the blue "SAVE" button. Without doing so, the subsequent cells will not work.

3. There are two modes: manual mode and training mode. The first mode is used for verifications by the TAs and the Professor. It is active with

![Manual Mode](https://imgur.com/bVqu5aR.png)

4. The training mode (mode_manual = False) has the same functionalities but with the printers deactivated. In either case, you need to have a network architecture configured.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import math
import random
import json
import matplotlib.pyplot as plt
from google.colab import drive
from sklearn.model_selection import train_test_split
drive.mount('/content/drive')
import ipywidgets as widgets
from IPython.display import display
# global numpy configurations
np.set_printoptions(precision=5, suppress=True, floatmode='fixed')
# %precision 5

"""# Defining the Architecture of NN
After running this cell, you must press the Save button so that the NN structure is loaded.
"""

saved_experiments = []

# Style wedgets
width_style = {'description_width': '70px'}
layout_width = widgets.Layout(width='200px')
slider_layout = widgets.Layout(width='120px')
# Creating widgets
text_input = widgets.Textarea(
    value="""You should train neural networks using different values of the regularization parameter λ,
and different network architectures. You may decide which architectures to evaluate. For example,
you might test networks with 1, 2, 3, and 4 hidden layers, and vary the number of neurons per layer,
such as 2, 4, 8, and 16. Examples: [1 2 1], [2 4 3 2]
""",
    description='Instructions:',
    layout=widgets.Layout(width='80%', height='110px')
)
input_layer = widgets.Dropdown(
    options=[i for i in range(1, 17)],
    value=1,
    description='📱input_layer',
    layout=slider_layout,
    style=width_style
)
hidden_layer_1 = widgets.Dropdown(
    options=[i for i in range(0, 17)],
    value=2,
    description='📲 Hidden_1',
    layout=slider_layout,
    style=width_style
)
hidden_layer_2 = widgets.Dropdown(
    options=[i for i in range(0, 17)],
    value=0,
    description='📲 Hidden_2',
    layout=slider_layout,
    style=width_style
)
hidden_layer_3 = widgets.Dropdown(
    options=[i for i in range(0, 17)],
    value=0,
    description='📲 Hidden__3',
    layout=slider_layout,
    style=width_style
)
hidden_layer_4 = widgets.Dropdown(
    options=[i for i in range(0, 17)],
    value=0,
    description='📲 Hidden__4',
    layout=slider_layout,
    style=width_style
)
output_layer = widgets.Dropdown(
    options=[i for i in range(1, 17)],
    value=1,
    description='📱 output_layer',
    layout=slider_layout,
    style=width_style
)
ui_horizontal = widgets.HBox(
    [input_layer, hidden_layer_1, hidden_layer_2, hidden_layer_3, hidden_layer_4, output_layer],
    layout=widgets.Layout(
    justify_content='space-between',
    width='80%'
)
)
input_regularization = widgets.FloatText(
    value=0.01,
    step=0.01,
    description='📈 Regularization (λ):',
    style={'description_width': '130px'},
    layout=layout_width
    )
btn_save = widgets.Button(description='Save', button_style='info')

# Saving the architecture
architecture = {}
def configure_architecture(n_in=None, n_hid=None, n_out=None, lmb=None):
  global architecture
  global reg_lambda
  # If parameters are passed (Automation), it uses them
  # If not (Button), it reads the widgets
  n_input = n_in if n_in is not None else input_layer.value
  n_hidden = n_hid if n_hid is not None else [h.value for h in [hidden_layer_1, hidden_layer_2, hidden_layer_3, hidden_layer_4] if h.value > 0]
  n_output = n_out if n_out is not None else output_layer.value
  reg_lambda = lmb if lmb is not None else input_regularization.value
  architecture['n_input'] = n_input
  architecture['n_hidden'] = n_hidden
  architecture['n_output'] = n_output
  architecture['reg_lambda'] = reg_lambda
  architecture['architecture'] = [n_input] + n_hidden + [n_output]
  print('*'*140)
  print(f'✅ Configuration saved:')
  print(f'❄️ Architecture: {architecture['architecture']} | λ: {reg_lambda}')

btn_save._click_handlers.callbacks = []
def on_button_clicked(monica):
    configure_architecture()
    # It is used for creating of list
    current_config = architecture.copy()
    saved_experiments.append(current_config)

btn_save.on_click(on_button_clicked)

display(text_input, ui_horizontal, input_regularization, btn_save)

# ===============================================================
# Testing data backprop_example1 and backprop_example2 in HW5
# ===============================================================
backprop_examples = {
    'backprop_example1': {
        'thetas': {
            'theta_1': np.array([
                [0.40000, 0.10000],
                [0.30000, 0.20000]
            ]),
            'theta_2': np.array([
                [0.70000, 0.50000, 0.60000]
            ])
        },
        'X': np.array([
            [0.13000],
            [0.42000]
        ]),
        'y': np.array([
            [0.90000],
            [0.23000]
        ])
    },

    'backprop_example2': {
        'thetas': {
            'theta_1': np.array([
                [0.42000, 0.15000, 0.40000],
                [0.72000, 0.10000, 0.54000],
                [0.01000, 0.19000, 0.42000],
                [0.30000, 0.35000, 0.68000]
            ]),
            'theta_2': np.array([
                [0.21000, 0.67000, 0.14000, 0.96000, 0.87000],
                [0.87000, 0.42000, 0.20000, 0.32000, 0.89000],
                [0.03000, 0.56000, 0.80000, 0.69000, 0.09000]
            ]),
            'theta_3': np.array([
                [0.04000, 0.87000, 0.42000, 0.53000],
                [0.17000, 0.10000, 0.95000, 0.69000]
            ])
        },
        'X': np.array([
            [0.32000, 0.68000],
            [0.83000, 0.02000]
        ]),
        'y': np.array([
            [0.75000, 0.98000],
            [0.75000, 0.28000]
        ])
    }
}

"""# Dynamic architecture based on the network's input configuration

It has a manual mode and an automatic mode. The first is for testing with the examples. The second is for training the neural network.
"""

def creating_thetas(X, mode_manual = True, example='backprop_example1'):

  if mode_manual:
    data = backprop_examples[example]
    thetas = data['thetas']
    X = data['X']
    y = data['y']
    return thetas, X, y

  # ===============================================================
  # Dynamic architecture based on the network's input configuration
  # ===============================================================
  if mode_manual == False:
    #print('*'*140)
    #print('Creating thetas in NN training mode ...')
    #print('*'*140)
    thetas = {}
    # Replacing the initial '1' with the number of columns of X
    architecture['architecture'][0] = X.shape[1]
    arch_list = architecture['architecture']
    for i in range(len(architecture['architecture']) - 1):
      name = f'theta_{i+1}'
      rows = architecture['architecture'][i+1]
      cols = architecture['architecture'][i] + 1
      thetas[name] = np.random.randn(rows, cols)
      #print(f"DEBUG: Thetas created: {list(thetas.keys())}")

  return thetas, None, None

"""# Prepare the data you want to work with (backprop_example2 or backprop_example1)"""

# ==================================================================
# Checking here the example !!!...
# ==================================================================

example='backprop_example2'
# ==================================================================
thetas, X, y = creating_thetas(_, mode_manual = True, example=example)
if X is None:
  print('='*140)
  print(f'The theta matrix data for training mode is \n {thetas}')
  print('='*140)
else:
  print('='*140)
  print(f'The testing data is working with the {example}')
  print('='*140)
  print(f'Thetas: {thetas}')
  print(f'X: {X}')
  print(f'y: {y}')

"""# Step forward propagation"""

def calculate_J(y_true, y_pred, thetas=None, lambd=0):

  # Using logistic regression
  m = len(y_true)
  term1 = y_true * np.log(y_pred)
  term2 = (1 - y_true) * np.log(1 - y_pred)
  J_aux = -np.sum(term1 + term2) / len(y_true)

  # Adding regularization
  reg_term = 0
  if thetas is not None and lambd > 0:
    for theta in thetas.values():
      reg_term += np.sum(np.square(theta[:, 1:]))
    reg_term = (lambd / (2 * m)) * reg_term

  return J_aux + reg_term

def forward_step(X, y, thetas, manual_mode = False,  example=example, lambd=0):

  m = len(X)
  total_J = 0
  all_activations = {f'instancia_{i}': {} for i in range(len(X))}

  # The activation function will be the sigmoid
  sigmoid = lambda z: 1 / (1 + np.exp(-z))

  # ==================================================================
  # Manual mode for checking
  # ==================================================================
  if manual_mode == True:

    for i in range(len(X)):
      x_instance = X[i:i+1]
      y_instance = y[i:i+1]

      print('*'*140)
      print(f'Forward step: Working in the manual mode with instance {i+1} and the example {example} ...')
      print('*'*140)
      print('\n')

      X_bias = np.hstack((np.ones((1, 1)), x_instance))
      activations = {}
      activations['a1'] = X_bias
      print(f"a1: {X_bias[0]}")
      current_a = X_bias
      for j, (name, theta) in enumerate(thetas.items()):
        z = current_a @ theta.T
        print(f'z{i+2}: {z[0]}')
        # calculating activation
        a_next = sigmoid(z)
        if j < len(thetas) - 1:
          current_a = np.hstack((np.ones((1, 1)), a_next))
          activations[f'a{j+2}'] = current_a
          print(f'a{j+2}: {activations[f"a{j+2}"][0]}')
        else:
          activations[f'a{j+2}'] = a_next
          print(f'a{j+2}: {activations[f'a{j+2}'][0]}')
      f_x = a_next[0]
      J = calculate_J(y_instance, f_x, thetas, lambd=0)
      total_J += J
      J_final = total_J / m
      all_activations[f'instancia_{i}'] = activations
      print(f'f(x) = {f_x}')
      print(f'The cost function J={J}')

  else:
      #print('Forward step: Working in the modo training of the NN model...')
      X_bias_total = np.hstack((np.ones((m, 1)), X))
      current_a = X_bias_total
      all_activations = {'a1': current_a}
      theta_list = list(thetas.values())

      for j, theta in enumerate(theta_list):
        z = current_a @ theta.T
        # Activations
        a_next = sigmoid(z)

        if j < len(theta_list) - 1:
          current_a = np.hstack((np.ones((m, 1)), a_next))
          all_activations[f'a{j+2}'] = current_a
        else:
          all_activations[f'a{j+2}'] = a_next
      # Calculating J final
      f_x_total = all_activations[f'a{len(theta_list) + 1}']
      J_final = calculate_J(y, f_x_total, thetas, lambd=0)

  return all_activations, J_final

"""# Step Backpropagation (Learning)"""

def backpropagation_step(X, y, activations_forward, manual_mode = True,  example=example, alpha=0.11):

  # Initializating accumulators for the gradients
  deltas_thetas_total = {f'delta_theta_{l}': np.zeros_like(thetas[f'theta_{l}']) for l in range(1, len(thetas)+1)}
  m = len(y)

  if manual_mode == True:
    print('*'*140)
    print(f'Backpropagation: Working in the manual mode with example {example} ...')
    print('*'*140)

    for i in range(len(X)):

      activations = activations_forward[f'instancia_{i}']
      y_instance = y[i:i+1]

      # ==================================================================
      # delta = (f(x) - y)
      # ==================================================================
      deltas = {}
      deltas_thetas = {}

      # Identification of last layer
      layer_index = [k for k in activations.keys() if k.startswith('a')]
      last_layer = sorted([int(k[1:]) for k in layer_index])[-1]

      # Output layer delta or prediction error
      f_x = activations[f'a{last_layer}']
      deltas[f'delta_{last_layer}'] = f_x - y_instance
      d_last = deltas[f'delta_{last_layer}']

      # Gradients of theta in (last_layer-1)
      deltas_thetas[f'delta_theta_{last_layer-1}'] = d_last.T @ activations[f'a{last_layer-1}']

      # Accumulation for the final average
      deltas_thetas_total[f'delta_theta_{last_layer-1}'] += deltas_thetas[f'delta_theta_{last_layer-1}']

      # Hidden layer delta's
      for l in range(last_layer - 1, 1, -1): # layer 1 (input) does not have a delta
        theta_l = thetas[f'theta_{l}']
        delta_next = deltas[f'delta_{l+1}']
        theta_no_bias = theta_l[:, 1:]

        a_current = activations[f'a{l}'][:, 1:]

        # Gradients of deltas
        error_term = delta_next @ theta_no_bias
        deltas[f'delta_{l}'] = error_term * a_current * (1 - a_current)

        # Gradients of thetas
        delta_l = deltas[f'delta_{l}']
        delta_theta = delta_l.T @ activations[f'a{l-1}']
        deltas_thetas[f'delta_theta_{l-1}'] = delta_theta

        # Acumulations
        deltas_thetas_total[f'delta_theta_{l-1}'] += delta_theta

        print('\n')
        print(f'Computing gradients in backpropagation with instances {i+1}...')
        print('='*140)
        print(f'Gradients delta: {deltas}')
        print(f'Gradients thetas: {deltas_thetas}')

    # ==================================================================
    # COMPUTING AVERAGE REGULARIZED GRADIENTS (Al final del modo manual)
    # ==================================================================
    print('\n' + '='*140)
    print("Computing the average (regularized) gradients:")
    print('='*140)
    for l in range(1, len(thetas) + 1):
      avg_grad = deltas_thetas_total[f'delta_theta_{l}'] /m
      # Deleting bias
      theta_reg = np.copy(thetas[f'theta_{l}'])
      theta_reg[:, 0] = 0
      # Regularized final gradient
      final_grad = avg_grad + (alpha/m) * theta_reg
      print(f'Final regularized gradients of theta{l}:')
      print(f'{final_grad}\n')

  else:
    #print(f'Backpropagation: Working in the training NN mode ...')

    activations = activations_forward
    layer_index = [k for k in activations.keys() if k.startswith('a')]
    last_layer = sorted([int(k[1:]) for k in layer_index])[-1]

    # Output layer delta or prediction error
    f_x = activations[f'a{last_layer}']

    deltas = {}
    deltas_thetas = {}
    deltas[f'delta_{last_layer}'] = f_x - y
    d_last = deltas[f'delta_{last_layer}']
    deltas_thetas_total[f'delta_theta_{last_layer-1}'] = d_last.T @ activations[f'a{last_layer-1}']

    # Hidden layer delta's
    for l in range(last_layer - 1, 1, -1):

      if f'theta_{l}' not in thetas:
                print(f"⚠️ Error: An attempt was made to access theta_l, but it does not exist.")
                print(f"Thetas disponibles: {list(thetas.keys())}")
                break

      theta_next_layer = thetas[f'theta_{l}']
      delta_of_next_layer = deltas[f'delta_{l+1}']

      # Deleting the bias
      theta_no_bias = theta_next_layer[:, 1:]

      # Assigning activations
      a_current = activations[f'a{l}'][:, 1:]
      error_term = delta_of_next_layer @ theta_no_bias
      deltas[f'delta_{l}'] = error_term * a_current * (1 - a_current)

      # Calculating The Anterior Theta Gradient
      delta_l = deltas[f'delta_{l}']
      # (neurons_l x m) @ (m x neurons_l-1)
      deltas_thetas[f'delta_theta_{l-1}'] = delta_l.T @ activations[f'a{l-1}']

      #print(f'delta_theta_{l-1}: {deltas_thetas[f'delta_theta_{l-1}'].shape}')
      #print(f'activations: {activations[f'a{l-1}'].shape}')

    # ==================================================================
    # COMPUTING AVERAGE REGULARIZED GRADIENTS (Igual al final del manual)
    # ==================================================================

    final_grad = {}
    for l in range(1, len(thetas) + 1):
        avg_grad = deltas_thetas_total[f'delta_theta_{l}'] / m
        theta_reg = np.copy(thetas[f'theta_{l}'])
        theta_reg[:, 0] = 0
        final_grad[f'delta_theta_{l}'] = avg_grad + (alpha/m) * theta_reg
        #print(f'Final regularized gradients of theta{l}:')
        #print(f'{final_grad}\n')

    return final_grad

"""# Manual Mode
                                                
"""

custom_layout = widgets.Layout(width='300px', height='80px')
btn_manual_mode = widgets.Button(description='Manual Mode (click)', button_style='info', layout=custom_layout)
btn_manual_mode.style.font_weight = 'bold'
btn_manual_mode.style.button_color = '#00bca8'
def on_click_manual(b):
  print('\n' + '='*50)
  print('Running manual mode ...')
  print('='*50 + '\n')
  # calling functions ...
  activations, j_val = forward_step(X, y, thetas, manual_mode=True)
  backpropagation_step(X, y, activations, manual_mode=True)
btn_manual_mode.on_click(on_click_manual)
display(btn_manual_mode)

"""# Training Mode (The assignment 5 starts here). Check the architecture saved."""

if architecture:
  print('*'*140)
  print(f'✅ Configuration saved:')
  print(f'❄️ Architecture: {architecture['architecture']} | λ: {reg_lambda}')
  print('*'*140)

"""# credit_approval dataset  """

dataset_credit = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_class/final_proj/credit_approval.csv')
dataset_credit.head(3)

"""# Analysis of the data"""

X = dataset_credit.drop(columns=['label'])
y = dataset_credit['label'].values

cat_cols = [col for col in X.columns if '_cat' in col]
unicos_por_categoria = X[cat_cols].nunique()
for col in cat_cols:
    print(f"\n Values in each col: {col}: {X[col].unique()}")

"""# Pre-processing data"""

cat_cols = [col for col in X.columns if '_cat' in col]

# Extract all unique labels
unique_labels = set()
for col in cat_cols:
    unique_labels.update(X[col].loc[X[col].apply(lambda x: isinstance(x, str))].unique())

# Generate unique random numbers between 41 and 100
available_numbers = np.arange(41, 101)
np.random.shuffle(available_numbers)

# Create one mapping dictionary
random_mapping = dict(zip(unique_labels, available_numbers))
X[cat_cols] = X[cat_cols].replace(random_mapping)

# Normalization
X_normal = (X - X.min()) / (X.max() - X.min())
X_normal.head(3)

"""# Cross-Validation data"""

# Cross-Validation (Stratified K-Fold) Training and test (no validation part)
def cross_validation_stratified(X_normal, y, k = 10):

  n = len(X_normal)
  index_total = np.arange(n)
  # Cutoff point for Cross-Validation, 70% training, 15% validation, 15% test dataset
  split_point = int(n * 0.85)
  train_index = index_total[:split_point]
  test_index = index_total[split_point:]
  # identification of labels for cross-validation
  y_train = y[train_index]
  # identification of each class for cross-validation
  idx_0 = train_index[y_train == 0]
  idx_1 = train_index[y_train == 1]
  # Shuffle
  np.random.shuffle(idx_0)
  np.random.shuffle(idx_1)
  # Split
  splits_0 = np.array_split(idx_0, k)
  splits_1 = np.array_split(idx_1, k)
  folds = []
  for i in range(k):
    fold_id = np.concatenate([splits_0[i], splits_1[i]])
    np.random.shuffle(fold_id)
    folds.append(fold_id)
  return folds, test_index
# Calling the function
folds_index, data_test_idx = cross_validation_stratified(X_normal, y, k = 10)

"""# Traning and evaluation of the NN using stratified cross-validation data"""

def train_validation_full_model(X_normal, y, folds_index, n_in, n_hid, n_out, lamb):

  configure_architecture(n_in=n_in, n_hid=n_hid, n_out=n_out, lmb=lamb)

  max_epochs = 100
  epsilon = 1e-5
  alpha = 0.11
  batch_size = 32

  fold_accuracies = []
  fold_losses = []
  fold_f1_scores = []

  for f_idx in range(len(folds_index)):

    #print('\n')
    #print('='*140)
    #print(f'Working with fold {f_idx + 1} in modo mini-batch ...')

    # ==================================================================
    # PREPARING THE FOLD DATA
    # ==================================================================

    val_idx = folds_index[f_idx]
    train_idx = np.concatenate([folds_index[j] for j in range(len(folds_index)) if j != f_idx])

    X_train_f = X_normal.iloc[train_idx].values
    y_train_f = y[train_idx].reshape(-1, 1)

    X_val_f = X_normal.iloc[val_idx].values
    y_val_f = y[val_idx].reshape(-1, 1)
    #print(f'X_train_f: {X_train_f.shape}')
    #print(f'y_train_f: {y_train_f.shape}')

    prev_J_epoch = float('inf')
    epoch_cost = 0

    # ==================================================================
    # THETA RESET
    # ==================================================================
    thetas_full, _, _ = creating_thetas(X_train_f, mode_manual = False)
    global thetas
    thetas = thetas_full

    # ==================================================================
    # TRAINING LOOP
    # ==================================================================
    for epoch in range(max_epochs):

      epoch_cost = 0
      # Shuffling is performed at the beginning of each epoch
      index = np.arange(len(X_train_f))
      np.random.shuffle(index)
      X_shuffled = X_train_f[index]
      y_shuffled = y_train_f[index]

      # Loop for mini-batch
      for start in range(0, len(X_train_f), batch_size):
        end = start + batch_size
        X_batch = X_shuffled[start:end]
        y_batch = y_shuffled[start:end]

        # Forward step
        activations, batch_J = forward_step(X_batch, y_batch, thetas, manual_mode = False,  example=example, lambd=0.01)
        epoch_cost += batch_J

        # Backpropagation step
        gradients = backpropagation_step(X_batch, y_batch, activations, manual_mode = False,  example=example, alpha=alpha)
        # Weight update, performed after each batch
        for l in range(1, len(thetas) + 1):
          thetas[f'theta_{l}'] -= alpha * gradients[f'delta_theta_{l}']

      # Stopping criterion: Evaluated at the end of the epoch (average of the batches)
      total_batches = np.ceil(len(X_train_f) / batch_size)
      avg_epoch_cost = epoch_cost / total_batches
      #print(f'Epoch {epoch + 1}/{max_epochs} | Cost: {avg_epoch_cost}')

      #if abs(prev_J_epoch - avg_epoch_cost) < epsilon:
        #print(f"Convergence in an epoch {epoch}. Cost: {avg_epoch_cost:.6f}")
        #break

      prev_J_epoch = avg_epoch_cost

      #if (epoch + 1) % 100 == 0:
        #print(f"Epoch {epoch + 1} - Cost average: {avg_epoch_cost:.6f}")

    # ==================================================================
    # EVALUATION
    # ==================================================================
    val_activations, val_loss = forward_step(X_val_f, y_val_f, thetas, manual_mode=False)
    #print(f'Validation loss: {val_loss}')
    # Prediction in the last layer
    last_layer = sorted([int(k[1:]) for k in val_activations.keys() if k.startswith('a')])[-1]
    y_pred = val_activations[f'a{last_layer}']
    # Accuracy
    pred_bin = (y_pred >= 0.5).astype(int)
    accuracy_fold = np.mean(pred_bin == y_val_f)
    fold_losses.append(val_loss)
    fold_accuracies.append(accuracy_fold)
    # F1-Score
    tp = np.sum((pred_bin == 1) & (y_val_f == 1))
    fp = np.sum((pred_bin == 1) & (y_val_f == 0))
    fn = np.sum((pred_bin == 0) & (y_val_f == 1))
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1_score = 2 * (precision * recall) / (precision + recall)
    fold_f1_scores.append(f1_score)
    #print(f"Results Fold {f_idx + 1}: Accuracy = {accuracy_fold:.4f}, F1-Score: {f1_score:.4f}, Loss = {val_loss:.4f}")
  return np.mean(fold_accuracies), np.mean(fold_f1_scores)

"""# Testing with different architectures on wdbc data"""

saved_experiments = []
display(text_input, ui_horizontal, input_regularization, btn_save)

"""# Table with results for wdbc data"""

final_results = []

print(f'🔬 Starting a batch of {len(saved_experiments)} experiments...')

# Iterate over yhe list of dictionaries
for i, config in enumerate(saved_experiments):
    #print(f"\n" + "·"*60)
    #print(f"TEST #{i+1}: Architecture {config['architecture']} | λ: {config['reg_lambda']}")
    # Calling training function using the dictionary keys
    try:
        avg_acc, avg_f1 = train_validation_full_model(
            X_normal,
            y,
            folds_index,
            n_in=config['n_input'],
            n_hid=config['n_hidden'],
            n_out=config['n_output'],
            lamb=config['reg_lambda']
        )
        # Save the results
        final_results.append({
            'ID': i + 1,
            'Hidden_Layers': len(config['n_hidden']),
            'Neurons': str(config['n_hidden']),
            'Lambda': config['reg_lambda'],
            'Mean_Accuracy': avg_acc,
            'Mean_F1_Score': avg_f1
        })
    except Exception as e:
        print(f'❌ Error in experiment {i+1}: {e}')

# Convert to DataFrame
df_summary = pd.DataFrame(final_results)

print('\n" + "🏆 FINAL RESULTS ORDERED BY ACCURACY')
display(df_summary.sort_values(by='Mean_Accuracy', ascending=False))

"""# Identify the best model from results with data (Deployment Model)"""

# Get the best configuration
best_idx = df_summary['Mean_Accuracy'].idxmax()
best_config = saved_experiments[best_idx]

print(f'🏆 Evaluating the winning Model on the 15% test set:')
print(f'Architecture: {best_config["architecture"]} | λ: {best_config["reg_lambda"]}\n')

all_indices = np.arange(len(X_normal))
train_indices = np.setdiff1d(all_indices, data_test_idx)

# Training data (85%)
X_train_final = X_normal.iloc[train_indices].values
y_train_final = y[train_indices].reshape(-1, 1)

# Shuffle index
shuffled_idx = np.random.permutation(len(X_train_final))

X_train_shuffled = X_train_final[shuffled_idx]
y_train_shuffled = y_train_final[shuffled_idx]

# Test data (15%)
X_test_final = X_normal.iloc[data_test_idx].values
y_test_final = y[data_test_idx].reshape(-1, 1)

# Variables for the Learning Curve
m_sizes = np.arange(5, len(X_train_final), 10)
test_costs_j = []
alpha = 0.5#0.11, 0.05

for m in m_sizes:
  # Training Subset Selection
  X_sub = X_train_shuffled[:m]
  y_sub = y_train_shuffled[:m]

  # configuration
  configure_architecture(
      n_in=X_sub.shape[1],
      n_hid=best_config['n_hidden'],
      n_out=best_config['n_output'],
      lmb=best_config['reg_lambda']
  )

  # Initialize Thetas
  thetas_final, _, _ = creating_thetas(X_sub, mode_manual=False)

  # Link to global state
  global thetas
  thetas = thetas_final

  for epoch in range(800):
    # Forward step
    activations, _ = forward_step(X_sub, y_sub, thetas, manual_mode=False)

    # Backpropagation step
    gradients = backpropagation_step(X_sub, y_sub, activations, manual_mode=False, alpha=alpha)

    # Weight update
    for l in range(1, len(thetas) + 1):
        thetas[f'theta_{l}'] -= alpha * gradients[f'delta_theta_{l}']

  # J cost
  _, j_test = forward_step(X_test_final, y_test_final, thetas, manual_mode=False)
  test_costs_j.append(j_test)

# Prediction
test_activations, _ = forward_step(X_test_final, y_test_final, thetas, manual_mode=False)
# Identify the last layer
last_layer_key = sorted([k for k in test_activations.keys() if k.startswith('a')])[-1]
y_prob = test_activations[last_layer_key]
y_pred = (y_prob >= 0.5).astype(int)

# metrics
final_accuracy = np.mean(y_pred == y_test_final)
tp = np.sum((y_pred == 1) & (y_test_final == 1))
fp = np.sum((y_pred == 1) & (y_test_final == 0))
fn = np.sum((y_pred == 0) & (y_test_final == 1))

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0
final_f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

# Plotting
plt.figure(figsize=(10, 5))
plt.plot(m_sizes, test_costs_j, color='blue', marker='o', label='Test Cost (J)')
plt.title(f'Learning Curve: J as a function of training instances wdbc data (alpha: {alpha})')
plt.xlabel('Number of Training Samples (m)')
plt.ylabel('Performance Cost (J) on Test Set')
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend()
plt.show()

print('*' * 60)
print(f'🎯 LEARNING CURVE COMPLETED')
print(f'Value alpha: {alpha}')
print('*' * 60)

print('*' * 60)
print(f'FINAL TEST SET RESULTS')
print(f'Final Accuracy: {final_accuracy:.4f}')
print(f'Final F1-Score: {final_f1:.4f}')
print('*' * 60)

"""# Random Forest"""

dataset_credit = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML_class/final_proj/credit_approval.csv')
dataset_credit.head(3)

# Entropy of the original dataset classes: unacceptable, acceptable, good, and very good.

def entropy(data):
  categories_probs = data.value_counts(normalize=True)
  log_categories_probs = np.log2(categories_probs)
  I_prob = -np.sum(categories_probs * log_categories_probs)
  return I_prob

# Calculates the weighted entropy of a dataset split by a specific attribute.
# Handles categorical (_cat) and numerical (_num) data differently.

def average_entropy(dataset, attribute_test_m):

  if len(dataset) == 0:
    return 0
  total_samples = len(dataset)
  entropy_total_sum = 0

  # Case categorical data
  if attribute_test_m.endswith('_cat'):
    #partition_atrib = dataset_car.groupby('buying_price').groups.items()
    partition_atrib = dataset.groupby(attribute_test_m).groups.items()
    count_class = []
    entropy_average = 0
    for categories, index in partition_atrib:
      sub_dataset = dataset['label'].loc[index]
      entropy_value = entropy(sub_dataset)
      count_class = sub_dataset.value_counts().sum()
      weight = count_class / dataset.shape[0]
      entropy_average += entropy_value * weight

  # Case numerical data (Gaussian density is used)
  if attribute_test_m.endswith('_num'):
    classes = dataset['label'].unique()
    total_samples = len(dataset)
    # Calculating parameters (mu, sigma) and the Prior P(class) for EACH CLASS separately
    class_info = {}
    for c in classes:
      subset_c = dataset[dataset['label'] == c][attribute_test_m]
      mu = subset_c.mean()
      sigma = subset_c.std() + 1e-9 # if division by zero
      prior = len(subset_c) / total_samples
      class_info[c] = {'mu': mu, 'sigma': sigma, 'prior': prior}

    # Calculating the posteriori
    entropy_total_sum = 0
    for x in dataset[attribute_test_m]:
      posteriors = {}
      for c, info in class_info.items():
        exponent = np.exp(-((x - info['mu'])**2 / (2 * info['sigma']**2)))
        gauss_density = (1 / (np.sqrt(2 * np.pi) * info['sigma'])) * exponent
        posteriors[c] = info['prior'] * gauss_density

      # Normalization
      total_p_x = sum(posteriors.values())
      if total_p_x > 0:
        instance_entropy = 0
        for c in classes:
          p_c_given_x = posteriors[c] / total_p_x
          if p_c_given_x > 0:
            instance_entropy -= p_c_given_x * np.log2(p_c_given_x)
            # Accumulating the entropy of this specific row.
        entropy_total_sum += instance_entropy

      else:
        entropy_total_sum += entropy(dataset['label'])
        # The final average is the sum of the individual uncertainties divided by N.
    entropy_average = entropy_total_sum / total_samples

  return entropy_average

def inf_Gain(entropy_each_attributes, entropy_class):
  max_gain = -1
  best_attribute = ''
  for key, value in entropy_each_attributes.items():
    inf_gain = entropy_class - value
    #print(f'The information gain for {key} is {inf_gain}')
    if inf_gain > max_gain:
            max_gain = inf_gain
            best_attribute = key
  return best_attribute, max_gain

# -----------------------------------------------------------------------------
# This function makes the step prediction
# -----------------------------------------------------------------------------

def predict(node, row):
  # If it is not a dictionary, it is a leaf (0 or 1)
  if not isinstance(node, dict):
    return node

  attribute = node['attribute']
  # If the attribute is numeric, we use the saved stats to decide the branch
  if 'stats' in node:
    stats = node['stats']
    x = row[attribute]
    # Using the same logic as in `build_tree` to decide which class 'x' belongs to
    probs = {}
    for c, info in stats.items():
      exponent = np.exp(-((x - info['mu'])**2 / (2 * info['sigma']**2)))
      f_X = (1 / (np.sqrt(2 * np.pi) * info['sigma'])) * exponent
      probs[c] = info['prior'] * f_X
    # The winning class tells us which key to look for in 'children'
    best_c = max(probs, key=probs.get)
    return predict(node['children'][str(best_c)], row)
  # If it is categorical, the value is the direct key
  else:
    value = row[attribute]
    if value in node['children']:
      return predict(node['children'][value], row)
    else:
      # If the value does not exist, position at the first available branch
      return predict(list(node['children'].values())[0], row)


def accuracy_calculate(y_pred, y_testing):
  #accuracy
  y_true = np.array(y_testing)
  y_p = np.array(y_pred)
  count_pred_ok = np.sum(y_p == y_true)
  accuracy = count_pred_ok / len(y_true)

  return accuracy

def calculate_metrics(y_pred, y_true):
    tp = sum((p == 1 and t == 1) for p, t in zip(y_pred, y_true))
    tn = sum((p == 0 and t == 0) for p, t in zip(y_pred, y_true))
    fp = sum((p == 1 and t == 0) for p, t in zip(y_pred, y_true))
    fn = sum((p == 0 and t == 1) for p, t in zip(y_pred, y_true))

    accuracy = (tp + tn) / len(y_true) if len(y_true) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    return accuracy, precision, recall, f1

I_class_subset = entropy(dataset_credit['label'])
attributes = [col for col in dataset_credit.columns if col != 'label']
#attributes = ['attr8_num']
entropy_remaining_attributes = {attr: average_entropy(dataset_credit, attr) for attr in attributes}
print(f"Entropy of the remaining attributes:{entropy_remaining_attributes}")
# Calculating the best attribute
best_attribute, gain = inf_Gain(entropy_remaining_attributes, I_class_subset)
print('*'*100)
print(f'The attribute with the highest information gain is {best_attribute}')

def build_tree(dataset, L_attributes, current_depth=0, max_depth=5, min_samples_split=10, min_gain_criterion = 0.00001):

  # --------------------------- STOP CONDITIONS --------------------------------

  counts = dataset['label'].value_counts()
  majority_class = int(counts.idxmax())

  # Control 1. When it is a leaf node
  if len(counts) == 1 or len(L_attributes) == 0:
    return majority_class
  # ----------------------------------------------------------------------------
  # Control 2. When it is Maximum depth reached
  if current_depth >= max_depth:
    return majority_class
  # ----------------------------------------------------------------------------
  # Control 3. When there are minimal instances
  if len(dataset) < min_samples_split:
    return majority_class
  # ----------------------------------------------------------------------------


  # Calculating entropy in the subset
  I_class_subset = entropy(dataset['label'])
  #print(f"Entropía del subconjunto: {I_class_subset}")

  # Calculating average entropy of the remaining attributes
  entropy_remaining_attributes = {attr: average_entropy(dataset, attr) for attr in L_attributes}
  #print(f"Entropy of the remaining attributes:{entropy_remaining_attributes}")

  # Calculating the best attribute
  best_attribute, gain = inf_Gain(entropy_remaining_attributes, I_class_subset)
  #print(f"The best attribute: {best_attribute}")
  #print(f"Gain Information: {gain}")


  #  ------------ Control When we have minimal inf Gain  --------------
  if gain <= min_gain_criterion:
        # The majority decision of the current dataset
        leaf_class = dataset['label'].value_counts().idxmax()###
        #print(f"There is a leaf node due to zero gain {leaf_class}")
        return int(leaf_class)
  #  ---------------------------------------------------------------------------

  # Creting a new node
  node = {'attribute': best_attribute, 'children': {}}
  # Removing the leaf node found from L_attributes
  L_remaining = [col for col in L_attributes if col != best_attribute]

  # ----------------------------------------------------------------------------
  # We have 2 cases: 1. The best_attribute is categorical data (HW1) and
  # 2. The best_attribute is numerical data. Therefore, the division of nodes
  # depends on this.
  # ----------------------------------------------------------------------------

  # ----------------------------------------------------------------------------
  # Categorical data
  # ----------------------------------------------------------------------------

  if best_attribute.endswith('_cat'):

    for branch in dataset[best_attribute].unique():
      branch_mapping_to_class = dataset[dataset[best_attribute] == branch]['label']
      #counting how many times each class appears
      counts = branch_mapping_to_class.value_counts()  ###
      #print(f"branch: {branch}")
      #print(f"Class distribution:\n{counts}")
      # checking if there is only one class in the branch
      if len(counts) == 1:
            # It is leaf node
            leaf_class = counts.index[0].item() ###
            node['children'][branch] = leaf_class
            #print(f"Leaf node because only one class: {leaf_class}")
      elif not L_remaining:
            # If there are no more attributes, choosing the most frequent class (by majority).
                leaf_class = counts.idxmax().item() ###
                node['children'][branch] = leaf_class
                #print(f"Leaf node because there are no more attributes (L empty): {leaf_class}")
      else:
            #print('Continue dividing the data ...')
            #print(f"Testing of other attributes")
            subset_branch = dataset[dataset[best_attribute] == branch]
            # controlling the end of the dataset
            if len(subset_branch) < len(dataset):
              node['children'][branch] = build_tree(subset_branch, L_remaining)
              #print(f"The childre node in categorica data is {node}")
              #print("*"*50 + "Changing node division using numeric data")
            else:
              node['children'][branch] = counts.idxmax().item()
            #print("next stage --------" * 30)

  # ----------------------------------------------------------------------------
  # Numeric Case
  # ----------------------------------------------------------------------------
  else:
    stats = {}
    classes = dataset['label'].unique()
    for c in classes:
      subset_c = dataset[dataset['label'] == c][best_attribute]
      #class_key = int(c)
      stats[c] = {
          'mu': float(subset_c.mean()),
          'sigma': float(subset_c.std() + 1e-9),
          'prior': len(subset_c) / len(dataset)
      }
    # Creating the numerical nodo for the prediction function
    node['stats'] = stats

    # Calculating the class probability
    def class_probability(x):
      P_clase_X = {}
      for c, info in stats.items():
        exponent = np.exp(-((x - info['mu'])**2 / (2 * info['sigma']**2)))
        f_X = (1 / (np.sqrt(2 * np.pi) * info['sigma'])) * exponent
        P_clase_X[c] = info['prior'] * f_X
      return max(P_clase_X, key=P_clase_X.get)

    # Making the prediction based in the best attribute
    dataset_predictions = dataset[best_attribute].apply(class_probability)

    for c in classes:
      branch_key = str(c)
      subset_branch = dataset[dataset_predictions == c]
      if not subset_branch.empty and len(subset_branch) < len(dataset):
        node['children'][branch_key] = build_tree(subset_branch, L_remaining)
        #print(f"The childre node in numerical data is {node}")
      else:
        # It will be leaf
        node['children'][branch_key] = c

  return node

"""# Looking the construction of the tree"""

# Starting
print('Starting tree ...')
# Attribute list that will be tested
L_attributes = [col for col in dataset_credit.columns if col != 'label']
#L_attributes =['attr1_cat',	'attr2_cat', 'attr3_cat',	'attr4_cat',	'attr5_cat']
#L_attributes =['attr1_cat',	'attr6_num']

# --------- Using m atributes where m = sqrt(X), with x=L_attributes -----------

# Calculate sample size (Square Root)
n = len(L_attributes)
m = math.isqrt(n)

# Selecting m attributes of L_attributes
L_random = random.sample(L_attributes, m)
tree_final = build_tree(dataset_credit, L_attributes)
#tree_final

def to_native(obj):
    # Recursively converts any NumPy object to a native Python type
    if isinstance(obj, dict):
        # Casting keys to values
        return {str(k) if isinstance(k, (np.int64, np.int32)) else k: to_native(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [to_native(i) for i in obj]
    elif isinstance(obj, (np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.float64, np.float32)):
        return float(obj)
    return obj

tree_final_nativo = to_native(tree_final)
#print(json.dumps(tree_final_nativo, indent=4))

"""## Testing the tree model with current_depth=0, max_depth=5, min_samples_split=10, min_gain_criterion = 0.00001 and ALL ATTRIBUTES"""

X = dataset_credit.iloc[:, :-1]
y = dataset_credit.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                      random_state=100)
dataset_loan_train = pd.concat([X_train, y_train], axis=1)
L_attributes = [col for col in X_train.columns]
# m random attributes
n = len(L_attributes)
m = math.isqrt(n)
L_random = random.sample(L_attributes, m)
tree_model = build_tree(dataset_loan_train, L_attributes)
y_pred_test = []

for _, row in X_test.iterrows():
    y_pred_aux_test = predict(tree_model, row)
    y_pred_test.append(y_pred_aux_test)
#print(f'y_pred_test is {y_pred_test}')
y_pred_test = [int(val) for val in y_pred_test]
acc_pred_test = accuracy_calculate(y_pred_test, y_test)
print(f'The accuracy of the model with all of the attributes is {acc_pred_test}')
print(f'The class balance in y_test is {y_test.value_counts()}')
#tree_model

"""## Testing the tree model with current_depth=0, max_depth=5, min_samples_split=10, min_gain_criterion = 0.00001 and ALL ATTRIBUTES"""

X = dataset_credit.iloc[:, :-1]
y = dataset_credit.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
                                                      random_state=100)
dataset_loan_train = pd.concat([X_train, y_train], axis=1)
L_attributes = [col for col in X_train.columns]
# m random attributes
n = len(L_attributes)
m = math.isqrt(n)
L_random = random.sample(L_attributes, m)
tree_model = build_tree(dataset_loan_train, L_attributes)
y_pred_test = []

for _, row in X_test.iterrows():
    y_pred_aux_test = predict(tree_model, row)
    y_pred_test.append(y_pred_aux_test)
#print(f'y_pred_test is {y_pred_test}')
y_pred_test = [int(val) for val in y_pred_test]
acc_pred_test = accuracy_calculate(y_pred_test, y_test)
print(f'The accuracy of the model with all of the attributes is {acc_pred_test}')
print(f'The class balance in y_test is {y_test.value_counts()}')
#tree_model

"""## Testing the tree model with current_depth=0, max_depth=10, min_samples_split=5, min_gain_criterion = 1e-6 AND m ATTRIBUTES"""

X = dataset_credit.iloc[:, :-1]
y = dataset_credit.iloc[:, -1]
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
#                                                      random_state=100)
#dataset_loan_train = pd.concat([X_train, y_train], axis=1)
L_attributes = [col for col in X.columns]
# m random attributes
n = len(L_attributes)
m = math.isqrt(n)
L_random = random.sample(L_attributes, m)
tree_model = build_tree(dataset_credit, L_random)
#tree_model = build_tree(dataset_loan_train, L_attributes)
y_pred_test = []

for _, row in X_test.iterrows():
    y_pred_aux_test = predict(tree_model, row)
    y_pred_test.append(y_pred_aux_test)
#print(f'y_pred_test is {y_pred_test}')
y_pred_test = [int(val) for val in y_pred_test]
acc_pred_test = accuracy_calculate(y_pred_test, y_test)
print(f'The accuracy of the model with m attributes is {acc_pred_test}')
print(f'The class balance in y_test is {y_test.value_counts()}')

"""# Bagging"""

def bagging(dataset):
  dataset_bootstraps_train = []
  dataset_bootstraps_test = []
  bootstrap = dataset.sample(n=len(dataset), replace=True)
  index_no_using = dataset.index.difference(bootstrap.index)
  oob_dataset = dataset.loc[index_no_using]
  dataset_bootstraps_train = bootstrap
  dataset_bootstraps_test = oob_dataset
  return dataset_bootstraps_train, dataset_bootstraps_test

"""# Random Forest Model"""

N_tree = 3

# --------------  Separating the dataset for cross-validation  -------------------

# Setting aside the the 15% FINAL TEST set that is not included in the Cross-Validation.
df_shuffled = dataset_credit.sample(frac=1, random_state=42).reset_index(drop=True)
# Cutoff point for Cross-Validation, 70% training, 15% validation, 15% test dataset
split_data = int(len(df_shuffled) * 0.85)
# Here, Cross-Validation, 70% training, 15% validation
train_cross_validation = df_shuffled.iloc[:split_data]
# Here, testing dataset for generalizations, 15%
test_data = df_shuffled.iloc[split_data:]

# -----------  Performing cross-validation -------------------------------------

K_folds = 5
folds = np.array_split(train_cross_validation, K_folds)
all_fold_accuracies = []
# Loop cross-validation
for k in range(K_folds):
  # 15% validation
  val_fixed_fold = folds[k]
  # 70% training
  train_decision_tree = pd.concat([x for i, x in enumerate(folds) if i != k])
  # Reset for each new Fold
  models_list = []
  y_pred = []
  models_votes = []
  y_ensemble_final = []
  y_real_val = val_fixed_fold['label'].tolist()

  # For each model ...
  for i in range(N_tree):
    # Generate Bagging and Save
    dataset_bootstraps_train, dataset_bootstraps_test = bagging(train_decision_tree)
    # Selection of Random Attribute
    L_attributes = [col for col in dataset_bootstraps_train.columns if col != 'label']
    n = len(L_attributes)
    m = math.isqrt(n) #+ 4
    L_random = random.sample(L_attributes, m)
    tree_model = build_tree(dataset_bootstraps_train, L_random,
                            current_depth=0, max_depth=5,
                            min_samples_split=10, min_gain_criterion = 0.00001)
    models_list.append(tree_model)
    print(f'The tree {i+1} was trained with bootstrap {i+1}')
    # Prediction step
    rows_votes = []
    accuracies = []
    for _, row in val_fixed_fold.iterrows():
      y_pred= predict(tree_model, row)
      rows_votes.append(int(y_pred))
    # Saving the decision for each model
    models_votes.append(rows_votes)
    print('*'*100)
  print(f"We have {len(models_votes)} models making predictions")
  # zip(*models_votes) groups the predictions of each expert by column
  for row_votes in zip(*models_votes):
    most_frequent = max(set(row_votes), key=row_votes.count)
    y_ensemble_final.append(most_frequent)
  print(f"The final vote, after taking each expert's vote, is:{y_ensemble_final}")
  # Accuracy of the ensemble
  acc_ensemble = accuracy_calculate(y_ensemble_final, y_real_val)
  all_fold_accuracies.append(acc_ensemble)
  print(f"Ensemble accuracy fold {k+1} is {acc_ensemble} ")

# -------------- Final Cross-Validation Result ---------------------------------
final_cross_val_performance = np.mean(all_fold_accuracies)
print(f"Model performance in cross_validation: {final_cross_val_performance:.4f}")

# -----------  Evaluating the selected model with test data --------------------
y_real_final_test = test_data['label'].tolist()
final_expert_votes = []

print("Evaluating generalization on 15% of the final test data...")
# Returning the ensemble of learned tree
for tree in models_list:
  tree_preds = []
  for _, row in test_data.iterrows():
    tree_preds.append(int(predict(tree, row)))
  final_expert_votes.append(tree_preds)
# Ensemble Final Vote on test_final
y_final_ensemble_pred = []
for row_votes in zip(*final_expert_votes):
  vote = max(set(row_votes), key=row_votes.count)
  y_final_ensemble_pred.append(vote)

# ------------ Accuracy in generalization model --------------------------------
acc_generalization = accuracy_calculate(y_final_ensemble_pred, y_real_final_test)
print("-" * 100)
print(f"🔥🔥🔥 FINAL MODEL GENERALIZATION (Test Set 15%): {acc_generalization:.4f}")
print("-" * 100)

"""### Training random forests with different values of the ntree parameter: 1, 5, 10, 20, 30, 40, and 50."""

ntree_list = [1, 5, 10, 20, 30, 40, 50]
results_generalization = [] # To save the final result of each experiment
results_final = [] # for metrics in cross-validation


# --------------  Separating the dataset for cross-validation  -------------------

# We set aside the 15% FINAL TEST set that is not included in the Cross-Validation.
df_shuffled = dataset_credit.sample(frac=1, random_state=15).reset_index(drop=True)
# Cutoff point for Cross-Validation, 70% training, 15% validation, 15% test dataset
split_data = int(len(df_shuffled) * 0.85)
# Here, Cross-Validation, 70% training, 15% validation
train_cross_validation = df_shuffled.iloc[:split_data]
# Here, testing dataset for generalizations, 15%
test_data = df_shuffled.iloc[split_data:]

# GENERAL LOOP FOR EACH NTREE VALUE
for N_tree in ntree_list:
    print(f"\n\n" + "!"*30)
    print(f" Starting Random Forest with N_tree = {N_tree} ")
    print("!"*30 + "\n")

    # -----------  Performing cross-validation -------------------------------------
    # Lists to save metrics for each fold
    fold_accs, fold_precs, fold_recs, fold_f1s = [], [], [], []
    all_trees_this_exp = []
    K_folds = 5
    folds = np.array_split(train_cross_validation, K_folds)
    all_fold_accuracies = []
    # Loop cross-validation
    for k in range(K_folds):
      # 15% validation
      val_fixed_fold = folds[k]
      # 70% training
      train_decision_tree = pd.concat([x for i, x in enumerate(folds) if i != k])
      # Reset for each new Fold
      models_list = []
      y_pred = []
      models_votes = []
      y_ensemble_final = []
      y_real_val = val_fixed_fold['label'].tolist()

      # For each model ...
      for i in range(N_tree):
        # Generate Bagging and Save
        dataset_bootstraps_train, dataset_bootstraps_test = bagging(train_decision_tree)
        # Selection of Random Attribute
        L_attributes = [col for col in dataset_bootstraps_train.columns if col != 'label']
        n = len(L_attributes)
        m = math.isqrt(n) + 4
        L_random = random.sample(L_attributes, m)
        tree_model = build_tree(dataset_bootstraps_train, L_random,
                                current_depth=0, max_depth=5,
                                min_samples_split=10, min_gain_criterion = 0.00001)
        models_list.append(tree_model)
        #print(f'The tree {i+1} was trained with bootstrap {i+1}')
        # Prediction step
        all_trees_this_exp.append(tree_model)
        rows_votes = []
        accuracies = []
        for _, row in val_fixed_fold.iterrows():
          y_pred= predict(tree_model, row)
          rows_votes.append(int(y_pred))
        # Saving the decision for each model
        models_votes.append(rows_votes)
        #print('*'*100)
      y_ensemble_final = [] # Restart fold assembly
      #print(f"We have {len(models_votes)} models making predictions")
      # zip(*models_votes) groups the predictions of each expert by column
      for row_votes in zip(*models_votes):
        most_frequent = max(set(row_votes), key=row_votes.count)
        y_ensemble_final.append(most_frequent)
      #print(f"The final vote, after taking each expert's vote, is:{y_ensemble_final}")
      # Accuracy of the ensemble
      acc_ensemble = accuracy_calculate(y_ensemble_final, y_real_val)
      all_fold_accuracies.append(acc_ensemble)
      print(f"Ensemble accuracy fold {k+1} is {acc_ensemble} ")

      #Calculate fold metrics
      acc, prec, rec, f1 = calculate_metrics(y_ensemble_final, y_real_val)
      fold_accs.append(acc)
      fold_precs.append(prec)
      fold_recs.append(rec)
      fold_f1s.append(f1)
      #print(f"Fold {k+1} | Acc: {acc:.4f} | F1: {f1:.4f}")
    # Cross-Validation Average
    cv_acc = np.mean(fold_accs)
    cv_prec = np.mean(fold_precs)
    cv_rec = np.mean(fold_recs)
    cv_f1 = np.mean(fold_f1s)

    # -------------- Final Cross-Validation Result ---------------------------------
    final_cross_val_performance = np.mean(all_fold_accuracies)
    print(f"Model performance in cross_validation: {final_cross_val_performance:.4f}")

    # -----------  Evaluating the selected model with test data --------------------
    y_real_final_test = test_data['label'].tolist()
    final_expert_votes = []

    print("Evaluating generalization on 15% of the final test data...")
    # Returning the ensemble of learned tree
    for tree in all_trees_this_exp:
      tree_preds = []
      for _, row in test_data.iterrows():
        tree_preds.append(int(predict(tree, row)))
      final_expert_votes.append(tree_preds)
    # Ensemble Final Vote on test_final
    y_final_ensemble_pred = []
    for row_votes in zip(*final_expert_votes):
      vote = max(set(row_votes), key=row_votes.count)
      y_final_ensemble_pred.append(vote)

    # ------------ Accuracy in generalization model ----------------------------
    acc_generalization = accuracy_calculate(y_final_ensemble_pred, y_real_final_test)
    metrics_generalization = calculate_metrics(y_final_ensemble_pred, y_real_final_test)
    print("-" * 100)
    print(f"🔥🔥🔥 FINAL MODEL GENERALIZATION (With the test set 15%), ACCURACY, F1-SCORE: {acc_generalization:.4f}, {metrics_generalization[3]:.4f}")
    print("-" * 100)

    # ----------- Saving the results of this N_tree ----------------------------
    results_generalization.append({
        'N_tree': N_tree,
        'CV_Accuracy': final_cross_val_performance,
        'Gen_Accuracy': acc_generalization

    })

    results_final.append({
        'N_tree': N_tree,
        'CV_Accuracy': cv_acc,
        'CV_Precision': cv_prec,
        'CV_Recall': cv_rec,
        'CV_F1': cv_f1
    })

for N_tree in results_generalization:
    print(f"{N_tree['N_tree']:<10} | {N_tree['CV_Accuracy']:<15.4f} | {N_tree['Gen_Accuracy']:<15.4f}")

""" # Accuracy, precision, recall, and F1 score of the resulting random forest


"""

n_trees = [res['N_tree'] for res in results_final]
cv_acc_values = [res['CV_Accuracy'] for res in results_final]
cv_prec_values = [res['CV_Precision'] for res in results_final]
cv_rec_values = [res['CV_Recall'] for res in results_final]
cv_f1_values = [res['CV_F1'] for res in results_final]
fig, axs = plt.subplots(2, 2, figsize=(10, 8))
fig.suptitle('Dataset #1: Random Forest Performance (Stratified Cross-Validation)', fontsize=18)

# Accuracy
axs[0, 0].plot(n_trees, cv_acc_values, marker='o', linestyle='-', color='b', linewidth=2)
axs[0, 0].set_title('Graph 1: CV Accuracy vs. ntree', fontsize=14)
axs[0, 0].set_ylabel('Average Accuracy Score')
axs[0, 0].grid(True, linestyle='--', alpha=0.7)

# Precision
axs[0, 1].plot(n_trees, cv_prec_values, marker='s', linestyle='-', color='g', linewidth=2)
axs[0, 1].set_title('Graph 2: CV Precision vs. ntree', fontsize=14)
axs[0, 1].set_ylabel('Average Precision Score')
axs[0, 1].grid(True, linestyle='--', alpha=0.7)

# Recall
axs[1, 0].plot(n_trees, cv_rec_values, marker='^', linestyle='-', color='r', linewidth=2)
axs[1, 0].set_title('Graph 3: CV Recall vs. ntree', fontsize=14)
axs[1, 0].set_ylabel('Average Recall Score')
axs[1, 0].grid(True, linestyle='--', alpha=0.7)

# F1 Score
axs[1, 1].plot(n_trees, cv_f1_values, marker='d', linestyle='-', color='m', linewidth=2)
axs[1, 1].set_title('Graph 4: CV F1 Score vs. ntree', fontsize=14)
axs[1, 1].set_ylabel('Average F1 Score')
axs[1, 1].grid(True, linestyle='--', alpha=0.7)

for ax in axs.flat:
    ax.set_xlabel('Number of Trees (ntree)', fontsize=10)
    ax.set_xticks(n_trees)

plt.tight_layout(rect=[0, 0.03, 1, 0.96])

plt.show()